canonical: https://www.medizininformatik-initiative.de/fhir/core/modul-person
fhirVersion: 4.0.1
FSHOnly: false
applyExtensionMetadataToRoot: false
id: mii-ig-person-de-2024
name: MII_IG_Person_DE
status: active
version: 2024.0.0
packageId: de.medizininformatikinitiative.kerndatensatz.person
copyrightYear: 2019+
releaseLabel: ci-build
publisher:
  name: Medizininformatik Initiative
  url: https://www.medizininformatik-initiative.de/
dependencies:
  de.basisprofil.r4: 1.4.0
  de.medizininformatikinitiative.kerndatensatz.meta: 1.0.3
