name: CI (FHIR Validation)

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  CI_FHIR_VALIDATION:
    uses: medizininformatik-initiative/kerndatensatz-meta/.github/workflows/ci_fhir_validation.yml@master
    with:
      ref: ${{ github.event.pull_request.head.ref }}
    secrets: inherit
